name: Workflow_sequentiel

on : 
  push:
    tags:
        - 'release*'
env:
    VAR1 : Bonjour ! 
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Afficher la valeur de VAR1
        run: |
          echo "$VAR1" 

  job2: 
    needs: job1 
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: si job1 echou 
        run: |
            echo "le job1 a 2choué"
